version: '3'
services:

  earnipay-wallet-service:
    build:
      context: .
    env_file: .env
    container_name: 'earnipay-wallet-service'
    ports:
      - 5052:5052
    volumes:
      - .:/var/www/
      - /var/www/node_modules